### ISSUE TITLE
fix kerf management

### ISSUE THREAD

**Issue by Fran5ois** [JarrettR/QuickJoint#22] opened 2024-03-14 15:08 UTC
Thank you very much for your work on Quickjoint inkscape extension!
I was really pleased to find it. 

There is one thing that could be improved to make it practical though: kerf management. I am looking into your code right now to see what I can do, but since I don't know Python (yet) I thought I'd post this issue first...

Here is the issue:

- As one comment from 2021 on inkscape.org points out, the slots should decrease in size with kerf, not increase. That is, of course, in order to cancel the play.
- Also, the fingers should increase in size with kerf. Alternatively, each slot should decrease in width by twice the kerf.
- Eventually, some "ears" should be added on both fingers and slots to avoid round concave edges for a perfect fit. (see https://www.festi.info/boxes.py/ for example)

This is the first time I file an issue on github so I hope I am doing it right. Please let me know if you need more help or information from my side.

Kerf management, as you know, is key for a proper fit.

Thank you in advance for your good reception of this issue.

**Comment by JarrettR** [comment] 2024-03-14 21:58
Hello!

You are doing issues right, have no fear.


With regard to your issues:
1)
![issue1](https://github.com/JarrettR/QuickJoint/assets/6027644/291382be-07fc-4542-b19c-fee0edf80ec6)

2)
![issue2](https://github.com/JarrettR/QuickJoint/assets/6027644/d9f317d2-90b0-4122-9fd9-28a89e08de43)


Unless I'm misunderstanding, I think maybe you're using an old version. Try downloading again from Github again and trying that.

3) Can you post screenshots of what you mean?

**Comment by Fran5ois** [comment] 2024-03-19 11:12
Thanks a lot @JarrettR for your quick and kind reply!

1&2. Indeed, I downloaded an old version! Thank you very much, with the last version it is now working like a charm :D

3. Here is a screen shot of a .svg output from https://www.festi.info/boxes.py/ that illustrates what I mean by "ears".

![image](https://github.com/JarrettR/QuickJoint/assets/39618326/07be2561-da3c-4384-b395-dd83115dcce3)

Now to be honest, I have never tried yet to laser cut finger joints without these ears, so your version might just work as is... I will give it a go in a few days and let you know the result.

Again, allow me to express my sincere gratitude to you for this software and your answer :) you will save me a lot of time!!

**Comment by JarrettR** [comment] 2024-03-19 17:24
No worries!
Closing this issue, as 1 and 2 are satisfied. 3 is a duplicate of #7

**Closed as completed by JarrettR** 2024-03-19 17:24 UTC
